const startDateInputBox = document.querySelector("#booking_start_date"); // ID generated by simple_form (use chrome inspect to get it!)
const endDateInputBox = document.querySelector("#booking_end_date");
const displayBox = document.querySelector("#book_now");
const carPrice = document.querySelector("#car_price");


const displayPrice = () => {
  const startDate = startDateInputBox.value;
  const endDate = endDateInputBox.value;
  const days = (new Date(endDate) - new Date(startDate)) / (1000 * 3600 * 24); // calculate date diff!
  // const days2 = (Date.parse(endDate) - Date.parse(startDate)) / (1000 * 3600 * 24);

  const updatePrice = `
    <h6 class="card p-3 mt-3"> $${carPrice.innerText} x ${days} days
    <hr> <strong> Total  $${(carPrice.innerText * days).toFixed(2)} </strong></h6>
  `;

  displayBox.insertAdjacentHTML("beforeEnd", updatePrice);
};

// focusout event!!!!
endDateInputBox.addEventListener("focusout", (event) => {
  displayBox.innerHTML = "";
  displayPrice();
  // console.log("hello");
})
